In [17]:
import pandas as pd #library will be used to import dataset
import numpy as np #process the data
import seaborn as sb #used for pairplots in this example
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [18]:
dataset = pd.read_csv("BankNote_Authentication.csv")

In [19]:
X = dataset.iloc[ : , :4]
Y = dataset.iloc[ : , 5]

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size = 0.1, random_state=0)

In [21]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)
predictions = classifier.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions ))

              precision    recall  f1-score   support

           0       1.00      0.97      0.99        77
           1       0.97      1.00      0.98        61

    accuracy                           0.99       138
   macro avg       0.98      0.99      0.99       138
weighted avg       0.99      0.99      0.99       138

[[75  2]
 [ 0 61]]


In [25]:
from sklearn.svm import SVC
classifier = SVC()
classifier.fit(X_train, y_train)
predictions = classifier.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions ))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        77
           1       1.00      1.00      1.00        61

    accuracy                           1.00       138
   macro avg       1.00      1.00      1.00       138
weighted avg       1.00      1.00      1.00       138

[[77  0]
 [ 0 61]]


In [26]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)
predictions = classifier.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions ))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99        77
           1       0.98      1.00      0.99        61

    accuracy                           0.99       138
   macro avg       0.99      0.99      0.99       138
weighted avg       0.99      0.99      0.99       138

[[76  1]
 [ 0 61]]


In [27]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)
predictions = classifier.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions ))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99        77
           1       0.98      0.98      0.98        61

    accuracy                           0.99       138
   macro avg       0.99      0.99      0.99       138
weighted avg       0.99      0.99      0.99       138

[[76  1]
 [ 1 60]]


In [30]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(X_train, y_train)
predictions = classifier.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions ))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        77
           1       1.00      1.00      1.00        61

    accuracy                           1.00       138
   macro avg       1.00      1.00      1.00       138
weighted avg       1.00      1.00      1.00       138

[[77  0]
 [ 0 61]]


In [31]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)
predictions = classifier.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions ))

              precision    recall  f1-score   support

           0       0.88      0.86      0.87        77
           1       0.83      0.85      0.84        61

    accuracy                           0.86       138
   macro avg       0.85      0.85      0.85       138
weighted avg       0.86      0.86      0.86       138

[[66 11]
 [ 9 52]]
